config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  root to: "pages#index"

  get "login", to: "pages#show_login"
  post "login", to: "pages#new_login"
  get "logout", to: "pages#logout"

  post "orders/:id/edit", to:  "orders#edit"
  post "orders/:id", to: "orders#find"

  resources :orders
  resources :inventories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/inventory.rb
class Inventory < ApplicationRecord
        has_many :orders

        validates :product_name, presence: true
        validates :price, numericality: true

        validate :check_if_enough_stock
        
        

        def check_if_enough_stock
            if committed.to_i > in_stock.to_i then
                errors.add(:committed, "Not enough stock")
            end
        end

        def check_input
            if in_stock.to_i.nil? && committed.to_i.nil? && ordered.to_i.nil? then
                    errors.add(:in_stock, :committed, :ordered, "Must not be blank please input zero if none")
            end
        end

        
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
  end


  # GET /inventories/1
  # GET /inventories/1.json
  def show
      @inventory = Inventory.find(params[:id])
      
      @result = @inventory.in_stock.to_i - @inventory.committed.to_i + @inventory.ordered.to_i
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit

  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)
    

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:product_name, :in_stock, :committed, :ordered, :price)
    end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_with(model: inventory, local: true) do |form| %>
  <% if inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name %>
  </div>

   <div class="field">
    <%= form.label :price %>
    P<%= form.number_field :price %>

  </div>

  <div class="field">
    <%= form.label :in_stock %>
    <%= form.number_field :in_stock %>
  </div>

  <div class="field">
    <%= form.label :committed %>
    <%= form.number_field :committed %>
  </div>

  <div class="field">
    <%= form.label :ordered %>
    <%= form.number_field :ordered %>
  </div>


  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<%= render "shared/jumbotron", header: "Inventory", tag_line:"", alignment: "text-center" %>
<p id="notice"><%= notice %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Product name</th>
      <th>Price </th>
      <th>In stock</th>
      <th>Committed</th>
      <th>Ordered</th>
      <th>Available</th> 
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.product_name %></td>
        <td>P<%= inventory.price %></td>
        <td><%= inventory.in_stock %></td>
        <td><%= inventory.committed %></td>
        <td><%= inventory.ordered %></td>
        <td>       
            <% if inventory.in_stock.to_i - inventory.committed.to_i + inventory.ordered.to_i != 0 then %>
              <%= inventory.in_stock.to_i - inventory.committed.to_i + inventory.ordered.to_i%>  
            <% else %>
              <%= "No more stock" %>
            <% end %>  
        </td>
        <td><%= link_to 'Show', inventory %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory', new_inventory_path %> || <%= link_to 'Orders', orders_path %>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @inventory.product_name %>
</p>

<p>
  <strong>Price:</strong>
  P<%= @inventory.price %>
</p>

<p>
  <strong>In stock:</strong>
  <%= @inventory.in_stock %>
</p>

<p>
  <strong>Committed:</strong>
  <%= @inventory.committed  %>
</p>

<p>
  <strong>Ordered:</strong>
  <%= @inventory.ordered %>
</p>

<p>
  <strong>Available:</strong>
  <%= @result %>


</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>